Add networked package management.
This change implements a full suite of networked tix package management,
with support for installation, upgrading, uninstallation; with signed
release metadata and support for incompatible changes across releases.

Add tix(8) package management program with common subcommands.

Add tix-install(8) support for downloading packages and dependencies.

Add tix-upgrade(8) that upgrades installations via the network.

Add tix-autoupgrade(8) daemon for unattended upgrades and offer to enable
it during sysinstall(8).

Add tix-clean(8) for cleaning temporary and cached tix files.

Add tix-create(8) as the modernized replacement for tix-collection(8)
with a simpler interface with support for release signing and the new
metadata.

Add tix-fetch(8) that downloads files from releases and channels and
verifies the signatures.

Add tix-metabuild(8) support for release metadata and signing.

Add tix-release(8) that creates releases and channels, and signs their
information for publication.

Add tix-uninstall(8) for uninstalling packages.

Add sysinstall(8) questions about automatic upgrades.

Add installtest --network-upgrade test for whether network upgrades work.

Move metadata from upgrade.conf(5) to collection.conf(5).

Document all the tix package management programs.

Promote the libssl, signify, wget, and xz packages to the minimal set, so
minimal installations are able to install more packages.

diff --git a/tix/tix-repository b/tix/tix-repository
--- a/tix/tix-repository
+++ b/tix/tix-repository
@@ -21,7 +21,7 @@ set -e
 generation=3
 
 unset command
-unset repository
+unset directory
 
 operand=1
 dashdash=
@@ -50,7 +50,7 @@ for argument do
       command="$argument"
       operand=2
     elif [ $operand = 2 ]; then
-      repository="$argument"
+      directory="$argument"
       operand=3
     else
       echo "$0: unexpected extra operand $argument" >&2
@@ -70,8 +70,8 @@ if [ -z "$command" ]; then
   exit 1
 fi
 
-if [ -z "$repository" ]; then
-  echo "$0: error: No repository was specified" >&2
+if [ -z "$directory" ]; then
+  echo "$0: error: No directory was specified" >&2
   exit 1
 fi
 
@@ -80,10 +80,10 @@ if [ "$generation" != 3 ]; then
   exit 1
 fi
 
-cd "$repository"
-
 case "$command" in
 metadata)
+  cd "$directory"
+
   ls |
   grep -E '\.tix.tar.xz$' |
   grep -Eo '^[^.]*' |
